In [7]:
import pandas as pd
data = pd.read_csv("faa_ai_prelim.csv")

# view the content
print(data)

   UPDATED ENTRY_DATE EVENT_LCL_DATE EVENT_LCL_TIME LOC_CITY_NAME  \
0       No  19-FEB-16      19-FEB-16      00:45:00Z    MARSHVILLE
1       No  19-FEB-16      18-FEB-16      23:55:00Z     TAVERNIER
2       No  19-FEB-16      18-FEB-16      22:14:00Z       TRENTON
3       No  19-FEB-16      18-FEB-16      17:10:00Z     ASHEVILLE
4       No  19-FEB-16      18-FEB-16      00:26:00Z     TALKEETNA
..     ...        ...            ...            ...           ...
78      No  08-FEB-16      31-DEC-15      17:00:00Z   SAN ANTONIO
79      No  08-FEB-16      05-FEB-16      11:17:00Z      MARICOPA
80      No  08-FEB-16      05-FEB-16      23:02:00Z     SAN PEDRO
81      No  08-FEB-16      05-FEB-16      23:02:00Z     SAN PEDRO
82     Yes  02-FEB-16      02-FEB-16      01:52:00Z        MOBILE

    LOC_STATE_NAME LOC_CNTRY_NAME  \
0   North Carolina            NaN
1          Florida            NaN
2       New Jersey            NaN
3   North Carolina            NaN
4           Alaska            NaN
..             ...            ...
78           Texas            NaN
79         Arizona            NaN
80      California            NaN
81      California            NaN
82         Alabama            NaN

                                             RMK_TEXT EVENT_TYPE_DESC  \
0   AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...        Accident
1   AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...        Incident
2   AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...        Incident
3   AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...        Incident
4   AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...        Incident
..                                                ...             ...
78  AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...        Accident
79  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...        Accident
80  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...        Accident
81  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...        Accident
82  N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...        Accident

                   FSDO_DESC  ... PAX_INJ_NONE PAX_INJ_MINOR PAX_INJ_SERIOUS  \
0      FAA Charlotte FSDO-68  ...          NaN           NaN             NaN
1          FAA Miami FSDO-19  ...          NaN           NaN             NaN
2   FAA Philadelphia FSDO-17  ...          NaN           NaN             NaN
3      FAA Charlotte FSDO-68  ...          NaN           NaN             NaN
4      FAA Anchorage FSDO-03  ...          NaN           1.0             NaN
..                       ...  ...          ...           ...             ...
78   FAA San Antonio FSDO-17  ...          NaN           NaN             NaN
79    FAA Scottsdale FSDO-07  ...          NaN           NaN             NaN
80    FAA Long Beach FSDO-05  ...          NaN           NaN             NaN
81    FAA Long Beach FSDO-05  ...          NaN           NaN             NaN
82    FAA Birmingham FSDO-09  ...          NaN           NaN             NaN

   PAX_INJ_FATAL PAX_INJ_UNK  GRND_INJ_NONE GRND_INJ_MINOR GRND_INJ_SERIOUS  \
0            NaN         NaN            NaN            NaN              NaN
1            NaN         NaN            NaN            NaN              NaN
2            NaN         NaN            NaN            NaN              NaN
3            NaN         NaN            NaN            NaN              NaN
4            NaN         NaN            NaN            NaN              NaN
..           ...         ...            ...            ...              ...
78           NaN         NaN            NaN            NaN              NaN
79           NaN         NaN            NaN            NaN              NaN
80           NaN         NaN            NaN            NaN              NaN
81           NaN         NaN            NaN            NaN              NaN
82           NaN         NaN            NaN            NaN              NaN

   GRND_INJ_FATAL  GRND_INJ_UNK
0             NaN           NaN
1             NaN           NaN
2             NaN           NaN
3             NaN           NaN
4             NaN           NaN
..            ...           ...
78            NaN           NaN
79            NaN           NaN
80            NaN           NaN
81            NaN           NaN
82            NaN           NaN

[83 rows x 42 columns]

In [8]:

# data shape
shape = data.shape
  
print(shape)

(83, 42)

In [10]:
columns = data.columns
print(columns)

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

In [13]:
print(data["ACFT_MAKE_NAME"], data['LOC_STATE_NAME'], data['ACFT_MODEL_NAME'], data["RMK_TEXT"], data['FLT_PHASE'],
     data['EVENT_TYPE_DESC'], data['FATAL_FLAG'])

0              BEECH
1               VANS
2             CESSNA
3            LANCAIR
4             CESSNA
           ...
78           AERONCA
79    NORTH AMERICAN
80          CHAMPION
81             BEECH
82            CESSNA
Name: ACFT_MAKE_NAME, Length: 83, dtype: object 0     North Carolina
1            Florida
2         New Jersey
3     North Carolina
4             Alaska
           ...
78             Texas
79           Arizona
80        California
81        California
82           Alabama
Name: LOC_STATE_NAME, Length: 83, dtype: object 0        36
1       RV7
2       172
3       235
4       172
      ...
78     O58B
79      F51
80    8KCAB
81       35
82      182
Name: ACFT_MODEL_NAME, Length: 83, dtype: object 0     AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...
1     AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...
2     AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...
3     AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...
4     AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...
                            ...
78    AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...
79    AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...
80    N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
81    N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
82    N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...
Name: RMK_TEXT, Length: 83, dtype: object 0      UNKNOWN (UNK)
1      LANDING (LDG)
2     APPROACH (APR)
3      LANDING (LDG)
4      LANDING (LDG)
           ...
78     LANDING (LDG)
79     UNKNOWN (UNK)
80     UNKNOWN (UNK)
81     UNKNOWN (UNK)
82     UNKNOWN (UNK)
Name: FLT_PHASE, Length: 83, dtype: object 0     Accident
1     Incident
2     Incident
3     Incident
4     Incident
        ...
78    Accident
79    Accident
80    Accident
81    Accident
82    Accident
Name: EVENT_TYPE_DESC, Length: 83, dtype: object 0     Yes
1     NaN
2     NaN
3     NaN
4     NaN
     ...
78    NaN
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

In [15]:
print(data.isna().sum())

UPDATED                 0
ENTRY_DATE              0
EVENT_LCL_DATE          0
EVENT_LCL_TIME          0
LOC_CITY_NAME           0
LOC_STATE_NAME          0
LOC_CNTRY_NAME         81
RMK_TEXT                0
EVENT_TYPE_DESC         0
FSDO_DESC               2
REGIST_NBR              0
FLT_NBR                77
ACFT_OPRTR             76
ACFT_MAKE_NAME          5
ACFT_MODEL_NAME         4
ACFT_MISSING_FLAG      83
ACFT_DMG_DESC           1
FLT_ACTIVITY           70
FLT_PHASE               1
FAR_PART               82
MAX_INJ_LVL             3
FATAL_FLAG             75
FLT_CRW_INJ_NONE       19
FLT_CRW_INJ_MINOR      77
FLT_CRW_INJ_SERIOUS    82
FLT_CRW_INJ_FATAL      75
FLT_CRW_INJ_UNK        83
CBN_CRW_INJ_NONE       83
CBN_CRW_INJ_MINOR      83
CBN_CRW_INJ_SERIOUS    83
CBN_CRW_INJ_FATAL      83
CBN_CRW_INJ_UNK        82
PAX_INJ_NONE           66
PAX_INJ_MINOR          82
PAX_INJ_SERIOUS        80
PAX_INJ_FATAL          82
PAX_INJ_UNK            83
GRND_INJ_NONE          83
GRND_INJ_MINOR         83
GRND_INJ_SERIOUS       83
GRND_INJ_FATAL         83
GRND_INJ_UNK           82
dtype: int64

In [21]:
data["FATAL_FLAG"].fillna('No',inplace=True)
print(data["FATAL_FLAG"])

0     Yes
1      No
2      No
3      No
4      No
     ...
78     No
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

In [23]:
data.dropna(subset = ['ACFT_MAKE_NAME'], inplace=True)
print(data)

   UPDATED ENTRY_DATE EVENT_LCL_DATE EVENT_LCL_TIME LOC_CITY_NAME  \
0       No  19-FEB-16      19-FEB-16      00:45:00Z    MARSHVILLE
1       No  19-FEB-16      18-FEB-16      23:55:00Z     TAVERNIER
2       No  19-FEB-16      18-FEB-16      22:14:00Z       TRENTON
3       No  19-FEB-16      18-FEB-16      17:10:00Z     ASHEVILLE
4       No  19-FEB-16      18-FEB-16      00:26:00Z     TALKEETNA
..     ...        ...            ...            ...           ...
78      No  08-FEB-16      31-DEC-15      17:00:00Z   SAN ANTONIO
79      No  08-FEB-16      05-FEB-16      11:17:00Z      MARICOPA
80      No  08-FEB-16      05-FEB-16      23:02:00Z     SAN PEDRO
81      No  08-FEB-16      05-FEB-16      23:02:00Z     SAN PEDRO
82     Yes  02-FEB-16      02-FEB-16      01:52:00Z        MOBILE

    LOC_STATE_NAME LOC_CNTRY_NAME  \
0   North Carolina            NaN
1          Florida            NaN
2       New Jersey            NaN
3   North Carolina            NaN
4           Alaska            NaN
..             ...            ...
78           Texas            NaN
79         Arizona            NaN
80      California            NaN
81      California            NaN
82         Alabama            NaN

                                             RMK_TEXT EVENT_TYPE_DESC  \
0   AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...        Accident
1   AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...        Incident
2   AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...        Incident
3   AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...        Incident
4   AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...        Incident
..                                                ...             ...
78  AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...        Accident
79  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...        Accident
80  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...        Accident
81  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...        Accident
82  N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...        Accident

                   FSDO_DESC  ... PAX_INJ_NONE PAX_INJ_MINOR PAX_INJ_SERIOUS  \
0      FAA Charlotte FSDO-68  ...          NaN           NaN             NaN
1          FAA Miami FSDO-19  ...          NaN           NaN             NaN
2   FAA Philadelphia FSDO-17  ...          NaN           NaN             NaN
3      FAA Charlotte FSDO-68  ...          NaN           NaN             NaN
4      FAA Anchorage FSDO-03  ...          NaN           1.0             NaN
..                       ...  ...          ...           ...             ...
78   FAA San Antonio FSDO-17  ...          NaN           NaN             NaN
79    FAA Scottsdale FSDO-07  ...          NaN           NaN             NaN
80    FAA Long Beach FSDO-05  ...          NaN           NaN             NaN
81    FAA Long Beach FSDO-05  ...          NaN           NaN             NaN
82    FAA Birmingham FSDO-09  ...          NaN           NaN             NaN

   PAX_INJ_FATAL PAX_INJ_UNK  GRND_INJ_NONE GRND_INJ_MINOR GRND_INJ_SERIOUS  \
0            NaN         NaN            NaN            NaN              NaN
1            NaN         NaN            NaN            NaN              NaN
2            NaN         NaN            NaN            NaN              NaN
3            NaN         NaN            NaN            NaN              NaN
4            NaN         NaN            NaN            NaN              NaN
..           ...         ...            ...            ...              ...
78           NaN         NaN            NaN            NaN              NaN
79           NaN         NaN            NaN            NaN              NaN
80           NaN         NaN            NaN            NaN              NaN
81           NaN         NaN            NaN            NaN              NaN
82           NaN         NaN            NaN            NaN              NaN

   GRND_INJ_FATAL  GRND_INJ_UNK
0             NaN           NaN
1             NaN           NaN
2             NaN           NaN
3             NaN           NaN
4             NaN           NaN
..            ...           ...
78            NaN           NaN
79            NaN           NaN
80            NaN           NaN
81            NaN           NaN
82            NaN           NaN

[78 rows x 42 columns]